### ISSUE TITLE
solaris 11, compilation failed

### ISSUE THREAD

**Issue by tankf33der** [edubart/nelua-lang#116]
```
$ gmake
<SKIP>
rpmalloc/rpmalloc.c:162:15: error: conflicting types for â€˜madviseâ€™
  162 |    extern int madvise(caddr_t, size_t, int);
      |               ^~~~~~~
In file included from rpmalloc/rpmalloc.c:155:
/usr/include/sys/mman.h:232:12: note: previous declaration of â€˜madviseâ€™ was here
  232 | extern int madvise(void *, size_t, int);
      |            ^~~~~~~
gmake[1]: *** [Makefile:63: nelua-lua] Error 1
$
```

This diff helped here:
```
bash-5.0$ git diff
diff --git a/src/rpmalloc/rpmalloc.c b/src/rpmalloc/rpmalloc.c
index 282a1dc..1d37e17 100644
--- a/src/rpmalloc/rpmalloc.c
+++ b/src/rpmalloc/rpmalloc.c
@@ -159,7 +159,7 @@ static DWORD fls_key;
 #    define MAP_HUGETLB MAP_ALIGNED_SUPER
 #  endif
 #  ifdef __sun
-   extern int madvise(caddr_t, size_t, int);
+   extern int madvise(void *, size_t, int);
 #  endif
 #  ifndef MAP_UNINITIALIZED
 #    define MAP_UNINITIALIZED 0
$
```

You have to handle Solaris 10 and 11.

**Comment by edubart** [comment]
Looks like rpmalloc is not supported there, you could build with `gmake NO_RPMALLOC=1`

**Comment by tankf33der** [comment]
RPMALLOC is supported for Solaris 11, it works.

Just add detection for Solaris 10 and 11.

**Comment by edubart** [comment]
I've reported the issue to rpmalloc project, and meanwhile I've disabled it for non Windows/Linux/MacOS platforms in commit https://github.com/edubart/nelua-lang/commit/85cc4bbf575621adaad9b0de1364e28ff0c4d8a6, because rpmalloc may not work good on many exotic operating systems so it's better to leave it enabled only on systems that are known to be working well, otherwise disabled.

The rpmalloc allocator is only used to speed up the Nelua compiler, it's not a critical piece, if the rpmalloc project fixes this issue I may enable it for all Solaris again in the future.

**Comment by mjansson** [comment]
> RPMALLOC is supported for Solaris 11, it works.
> 
> Just add detection for Solaris 10 and 11.

@tankf33der do you know any preprocessor define that can be used to check if it’s Solaris 10 or 11 being targeted?

**Comment by tankf33der** [comment]
> @tankf33der do you know any preprocessor define that can be used to check if it’s Solaris 10 or 11 being targeted?

@mjansson I did not find direct way  for this in google.
