### ISSUE TITLE
Compiling lua code without local / global declarations?

### ISSUE THREAD

**Issue by MikeDX** [edubart/nelua-lang#12]
Is there a command line option, or a workaround to use nelua on simple code like:

```lua
a = 1
b = 2
print(a + b)
```

rather than

```lua
local a = 1
local b = 1
print(a + b)
```

I know issues arent a wishing well, and this really isn't an issue per se, but at this point I don't know a better place to ask :)

**Comment by edubart** [comment]
In short no, you should explicitly declare your variable as `local` or `global`. This was supported before but I concluded that it did more harm than good for the users, because it hides away many possible errors that could be caught at compile time and this leads to bad experiences while coding. I know this is possible in Lua, but not in Nelua, futhermore many people consider bad practice and dangerous doing that even in Lua. In the future there is the possibility to revisit this feature if I decide to implement the global `_G` table like in Lua, but would be optional.

So the correct code for your example in Nelua is:
```lua
global a = 1
global b = 2
print(a + b)
```

You can ask more question in the discord chat, the link is on the chat badge in the github home page.

**Comment by MikeDX** [comment]
Thanks @edubart that makes sense. I'll join the discord since I'm very keen on the project! Feel free to close the issue.

**Comment by MetlHedd** [comment]
The invite link for discord server is invalid @edubart

**Comment by edubart** [comment]
@MetlHedd Thanks for notifying, I've fixed.
