### ISSUE TITLE
Bug in Lua coroutine mechanism

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#156]
They have reported a bug in Lua 5.4 that is in coroutine mechanism http://lua-users.org/lists/lua-l/2021-10/msg00123.html

The patch is provided by Roberto http://lua-users.org/lists/lua-l/2021-11/msg00015.html

In case Nelua is affected by it, it needs patching; else, simply ignore this ticket.

**Comment by edubart** [comment]
Nelua does not have the function `coroutine.wrap` yet, because the language lacks support for closures yet, so it is impossible for Nelua to be affected by that bug. Furthermore the Nelua's coroutine implementation is hugely different from the Lua implementation, as it is implemented with CPU instructions via the [minicoro library](https://github.com/edubart/minicoro), while in Lua it is interpreted and not at the hardware level.

**Comment by stefanos82** [comment]
Thank you for letting me know; cheers :+1:

**Comment by XeroOl** [comment]
My understanding was that nelua uses lua in the preprocessor. Can that code not use `coroutine.wrap`?
