### ISSUE TITLE
Copyright timespan needs update

### ISSUE THREAD

**Issue by stefanos82** [edubart/nelua-lang#239]
In the following line 

https://github.com/edubart/nelua-lang/blob/dc479bf4b1ad1335d9caa6cdbf282cc5979f06c0/lualib/nelua/runner.lua#L44

the year remained at `2022`.

Do you need it to get updated or should you remove it and leave it as `console.info('Copyright (C) Eduardo Bart (https://nelua.io/)')` ?

At first, I was thinking something like `console.info('Copyright (C) 2019-' .. os.date('%Y') ..' Eduardo Bart (https://nelua.io/)')` but then I asked myself, is it really necessary to have a copyright timespan?

**Comment by edubart** [comment]
I've updated the copyright year in https://github.com/edubart/nelua-lang/commit/58a189d794d9c2be51c970a434f2f6fd13bd88ac using your suggestion, but with a minimum year (in case the system clock is skewed).

> is it really necessary to have a copyright timespan?

I think that according to some law, a copyright has life time that eventually ends, it does not hold forever. Imagine we are thousands years in the future and someone wants to use this very old code, since the copyright may have ended centuries ago, the code will be of public domain and the copyright will have no meaning anymore. I think that to hold copyright forever, we have to effectively keep bumping the copyright year forever. I am not sure if it works really this way, but that is what I've always assumed.

**Comment by stefanos82** [comment]
I have completely forgot about the legal obstacles various countries put on us developers.

Thank you for reminding me that!

**Comment by Andre-LA** [comment]
The Godot developers uses "present" on the lifespan, like: "Copyright (c) 2014-**present** Godot Engine contributors (see AUTHORS.md)"

https://github.com/godotengine/godot/blob/37d51d2cb7f6e47bef8329887e9e1740a914dc4e/core/math/a_star.cpp#L8
