### ISSUE TITLE
C primitives for float, double and bool

### ISSUE THREAD

**Issue by Andre-LA** [edubart/nelua-lang#6]
When binding to Raylib, there are some procedures with float, double and bool as argument/return types, however there is no C primitives to these.

**Comment by edubart** [comment]
There is, `float32`, `float64`, and `boolean` is exactly `float`, `double` and `bool` in C code. There is no alias for them as `cfloat`, `cdouble` or `cbool` because it would be redundant and to keep the language types more compact.

You can view this table to know the equivalent number types in Nelua and C 
https://nelua.io/overview/#numbers

**Comment by edubart** [comment]
Another note `integer` and `number` types should be avoided in C imports because they are configurable. Like the user could change `integer` to `int32` instead `int64` and `number` to `float32` instead of `float64`. This kind of thing is also possible in Lua.

**Comment by Andre-LA** [comment]
oh ok, I was already using float32, float64 and boolean, but didn't knew it was already the correct way XD.

I'll close the issue then.
