### ISSUE TITLE
Question: plans on error handling?

### ISSUE THREAD

**Issue by mna** [edubart/nelua-lang#60]
Hello,

I really like what I've read on nelua so far, being a big fan of Lua I love the idea of using a similar language with native code, AOT, low-level properties. I noticed in the Differences page (https://nelua.io/diffs/), `[x]pcall` are marked as never/n.a. Does that mean that error handling is to be done strictly via the `return nil, err` idiom, and there wouldn't be a way to recover from a runtime panic? Or is it TBD later in the project?

Thanks,
Martin

**Comment by edubart** [comment]
Currently error handling must be done with return values as mentioned. And `error` will panic making the application exit.

The problem with `pcall` is that it changes the program control flow and this has many consequences for other planned language features (such as GC, defer and closures), thus this was deferred to be researched in the future, but is not out of the table. Recently Nelua got coroutines support and this is going to be maintained, and I have on my side an experimental implementation of `pcall` and `error` style error handling implemented with coroutines, and anyone could do this at the moment. Coroutines changes the program control flow similar as pcall does, but does incur extra costs like a new stack allocation. `pcall` could also be implemented in the future using C `longjmp` `setjmp` however at the moment this conflicts with the language GC and is not supported on every platform. Other option is to use C++ exceptions, as but then the language would require a C++ compiler. Another option is to use raw assembly instructions for context switching like coroutine is doing at the moment, however unlike coroutines, we could avoid extra allocation stack allocation. Anyway this is something to be researched in the future and I cannot say if Nelua will ever get `pcall` officially or not at the moment.

On the other side, for low level programmers I recommend returning errors on function instead of using `pcall` or exception style code, this is usually more efficient, less troublesome and makes the code more understandable and predictable. Of course it can make some code more boilerplate, but usually pays off, I usually do my Nelua code in this style and that's why this is a feature I'm not anxious about. But as a Lua user I also wish `pcall` support someday if it's implementation fits well with the rest of the language.

**Comment by mna** [comment]
Thanks for sharing your thoughts, that makes a lot of sense. As someone who writes a lot of Go code as well, I do appreciate using simple error values for errors (especially in languages with multiple return values, where it doesn't have some of the downsides of e.g. C). Didn't know the coroutines implementation had landed, will definitely try this out.
